"""Add Order Models

Revision ID: 87a9eabf8e13
Revises: 193ed6b6f6cd
Create Date: 2025-02-16 02:17:27.241585

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from app.models import PydanticJSONType, PydanticJSONListType, \
    Contacts, Delivery, CartProduct

# revision identifiers, used by Alembic.
revision = '87a9eabf8e13'
down_revision = '193ed6b6f6cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('contacts', PydanticJSONType(Contacts), nullable=False),
    sa.Column('delivery', PydanticJSONType(Delivery), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'UAH', name='currency'), nullable=False),
    sa.Column('basketOrder', PydanticJSONListType(CartProduct), nullable=False),
    sa.Column('mailing', sa.Boolean(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payment_status', sa.Enum('CREATED', 'PROCESSING', 'HOLD', 'SUCCESS', 'FAILURE', 'REVERSED', 'EXPIRED', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoiceId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoiceId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
