"""Initial migration

Revision ID: c369db024387
Revises: 
Create Date: 2025-01-12 19:48:48.996243

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c369db024387'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriber',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mailing_language', sa.Enum('EN', 'UK', name='mailinglanguage'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriber_email'), 'subscriber', ['email'], unique=True)
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('product',
    sa.Column('category', sa.Enum('CARABINER', 'BOOK_HOLDER', 'CHOKER', 'PLATE', 'SOAP_HOLDER', 'IVAN_THE_TABLE', name='productcategory'), nullable=False),
    sa.Column('title_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('title_uk', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('material_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('material_uk', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('price_uah', sa.Float(), nullable=False),
    sa.Column('size', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('weight', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('tag', sa.Enum('BUNNY', 'HEART', 'SHURIKEN', 'SPIKELET', name='carabinertags'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_image',
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'order', name='unique_product_image_order')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_image')
    op.drop_table('product')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_subscriber_email'), table_name='subscriber')
    op.drop_table('subscriber')
    # ### end Alembic commands ###
